abbr -a -- g 'git status'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- g 'git status'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- gb 'git checkout -b'
abbr -a -- g git
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- g git
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- g git
abbr -a -- vi nvim
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- g git
abbr -a -- vi nvim
abbr -a -- cdr 'cd ~/projects/rocket_jump'
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- g git
abbr -a -- vi nvim
abbr -a -- cdr 'cd ~/projects/rocket_jump'
abbr -a -- saveabbr 'abbr >> ~/.config/fish/conf.d/abbrs.fish'
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- g git
abbr -a -- vi nvim
abbr -a -- ga 'git add'
abbr -a -- gap 'git add -p'
abbr -a -- gd 'git diff'
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- vi nvim
abbr -a -- ga 'git add'
abbr -a -- gap 'git add -p'
abbr -a -- gd 'git diff'
abbr -a -- g 'git status'
abbr -a -- cdr 'cd ~/projects/rocket_jump'
abbr -a -- saveabbr 'abbr >> ~/.config/fish/conf.d/abbrs.fish'
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- vi nvim
abbr -a -- ga 'git add'
abbr -a -- gap 'git add -p'
abbr -a -- gd 'git diff'
abbr -a -- g 'git status'
abbr -a -- gp 'git push'
abbr -a -- cdr 'cd ~/projects/rocket_jump'
abbr -a -- saveabbr 'abbr >> ~/.config/fish/conf.d/abbrs.fish'
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- vi nvim
abbr -a -- ga 'git add'
abbr -a -- gap 'git add -p'
abbr -a -- gd 'git diff'
abbr -a -- g 'git status'
abbr -a -- gp 'git push'
abbr -a -- gpr 'git pull --rebase'
abbr -a -- cdr 'cd ~/projects/rocket_jump'
abbr -a -- saveabbr 'abbr >> ~/.config/fish/conf.d/abbrs.fish'
abbr -a -- gb 'git checkout -b'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gpu 'git push -u origin $(git branch --show-current)'
abbr -a -- vi nvim
abbr -a -- ga 'git add'
abbr -a -- gap 'git add -p'
abbr -a -- gd 'git diff'
abbr -a -- g 'git status'
abbr -a -- gp 'git push'
